version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/ssl:/app/ssl
    image: surreal29/zack-cook-nginx
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    image: surreal29/zack-cook-api
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    image: surreal29/zack-cook-client
