version: '3'
services:
  client_dev:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    image: surreal29/zack-cook-client
