version: '3'
services:
  api_dev:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - '5000:5000'
    image: surreal29/zack-cook-api
    volumes:
      - ./api:/app
      - /app/node_modules
      - /app/nodemon
  client_dev:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '3000:3000'
    image: surreal29/zack-cook-client
